language: php

php:
  - 7.0
  - 7.1
  - 7.2

branches:
  only: master

install: composer install -n

scripts:
  - phpunit --bootstrap $TRAVIS_BUILD_DIR/vendor/autoload.php --configuration $TRAVIS_BUILD_DIR/unittest.xml